before_script:
  - env

image: $SERVER_LITE_DOCKER_IMAGE

stages:
  - ci
  - build

check:prebuilt:
  stage: ci
  script:
    - ls
    #- ./paddle/fluid/lite/tools/build.sh check_style

build:server:
  image: $SERVER_LITE_DOCKER_IMAGE
  stage: build
  cache:
    key: server_thirdparty
    paths:
        - build/third_party
  script:
    - echo "10.91.163.233 github.com" >> /etc/hosts
    - git config --system http.sslVerify false
    - ./paddle/fluid/lite/tools/build.sh build_test_server

build:mobile:
    stage: build
    image: $MOBILE_LITE_DOCKER_IMAGE
    cache:
        key: mobile_thirdparty
        paths:
            - $MOBILE_LITE_CACHE0
            - $MOBILE_LITE_CACHE1
    script:
        - ./paddle/fluid/lite/tools/build.sh build_test_arm
