before_script:
  - env

image: $SERVER_LITE_DOCKER_IMAGE

stages:
  - ci
  - build_server
  - build_mobile

check:prebuilt:
    tags:
        - lite
    stage: ci
    script:
        - rm -rf ~/.pip
        - pip install pre-commit
        - pre-commit install

        # merge the latest code
        - git config --global user.email "you@example.com"
        - git config --global user.name "Your Name"
        - git fetch origin incubate/lite
        - git merge --no-ff origin/incubate/lite

        - ./paddle/fluid/lite/tools/build.sh check_style
    cache:
        key: check_style
        paths:
            - /root/.cache

build:server:
    tags:
        - lite
    image: $SERVER_LITE_DOCKER_IMAGE
    stage: build_server
    cache:
        key: server_thirdparty
        paths:
            - build/third_party
            - /root/.ccache
    script:
        - apt install ccache
        - export http_proxy=$CI_PROXY
        - export https_proxy=$CI_PROXY

        # merge the latest code
        - git config --global user.email "you@example.com"
        - git config --global user.name "Your Name"
        - git fetch origin incubate/lite
        - git merge --no-ff origin/incubate/lite

        - mkdir -p build
        - cd build
        - ../paddle/fluid/lite/tools/build.sh cmake_x86
        - make extern_eigen3
        - make extern_boost
        - make framework_proto
        - make extern_warpctc
        - cd ..
        - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build/third_party/install/mklml/lib
        - ./paddle/fluid/lite/tools/build.sh build_test_server
    dependencies:
        - check:prebuilt

build:mobile:
    tags:
        - lite
    stage: build_mobile
    image: $MOBILE_LITE_DOCKER_IMAGE
    cache:
        key: mobile_thirdparty
        paths:
            - $MOBILE_LITE_CACHE0
            - $MOBILE_LITE_CACHE1
            - /root/.ccache
    script:
        - apt install ccache
        - export http_proxy=$CI_PROXY
        - export https_proxy=$CI_PROXY

        # merge the latest code
        - git config --global user.email "you@example.com"
        - git config --global user.name "Your Name"
        - git fetch origin incubate/lite
        - git merge --no-ff origin/incubate/lite

        - ./paddle/fluid/lite/tools/build.sh build_test_arm
    dependencies:
        - build:server
